import"./assets/main-Dnzr3yj7.js";import{s as _,l as u,b as L,a as A}from"./assets/custom-lessons-store-BSttwj8q.js";import{c as p}from"./assets/custom-lesson-presets-B74WAqg2.js";const n={search:"",category:"all",level:"all"},f=document.querySelector('[data-filter="search"]'),h=document.querySelector('[data-filter="level"]'),v=Array.from(document.querySelectorAll("[data-category]")),$={grammar:document.querySelector('[data-category-grid="grammar"]'),communication:document.querySelector('[data-category-grid="communication"]'),lexical:document.querySelector('[data-category-grid="lexical"]'),quick:document.querySelector('[data-category-grid="quick"]')},k={grammar:document.querySelector('[data-category-section="grammar"]'),communication:document.querySelector('[data-category-section="communication"]'),lexical:document.querySelector('[data-category-section="lexical"]'),quick:document.querySelector('[data-category-section="quick"]')},I={grammar:document.querySelector('[data-category-empty="grammar"]'),communication:document.querySelector('[data-category-empty="communication"]'),lexical:document.querySelector('[data-category-empty="lexical"]'),quick:document.querySelector('[data-category-empty="quick"]')},d=document.querySelector("[data-custom-section]"),g=document.querySelector("[data-custom-grid]"),y=document.querySelector("[data-custom-empty]"),s={total:document.querySelector("[data-stat-total]"),grammar:document.querySelector("[data-stat-grammar]"),communication:document.querySelector("[data-stat-communication]"),lexical:document.querySelector("[data-stat-lexical]"),quick:document.querySelector("[data-stat-quick]")};function S(t){return t.trim().toLowerCase()}function q(t){return String(t??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function x(){v.forEach(t=>{const e=t.dataset.category===n.category,a=t.dataset.category==="all"?n.category==="all":e;t.classList.toggle("chip--filled",a),t.setAttribute("aria-pressed",String(a))})}function E(t){var o;const e=((o=L[t.category])==null?void 0:o.label)??t.category,c=`lesson.html?topic=${encodeURIComponent(t.id)}&category=${encodeURIComponent(t.category)}&level=${encodeURIComponent(t.level)}&title=${encodeURIComponent(t.title)}&file=${encodeURIComponent(t.htmlPath)}`,a=Array.isArray(t.tags)?t.tags:[];return`
    <article class="lesson-card" data-lesson-id="${t.id}" data-category="${t.category}" data-level="${t.level}">
      <a class="lesson-card__link" href="${c}">
        <div class="lesson-card__meta">
          <span class="lesson-card__category">${e}</span>
          <span class="lesson-card__level" aria-label="Рівень">${t.level}</span>
        </div>
        <h3 class="lesson-card__title">${t.title}</h3>
        <p class="lesson-card__description">${t.description}</p>
        ${a.length?`<ul class="lesson-card__tags">${a.map(i=>`<li>${i}</li>`).join("")}</ul>`:""}
        <span class="lesson-card__cta">Перейти до матеріалу</span>
      </a>
    </article>
  `}function T(t){const e=(t.topicIds||[]).map(r=>u.find(l=>l.id===r)).filter(Boolean),c=Array.from(new Set(e.map(r=>r.level))).sort(),a=e.filter(r=>r.category==="grammar").length,o=e.filter(r=>r.category==="communication").length,i=e.filter(r=>r.category==="lexical").length;return{topics:e,levels:c,grammarCount:a,communicationCount:o,lexicalCount:i}}function b(t){const e=T(t),c=t.description||e.topics.map(a=>a.title).slice(0,3).join(", ");return t.level||e.levels.length&&e.levels.join(", "),t.source,`
    <article class="lesson-card lesson-card--custom" data-custom-lesson-id="${t.id}" data-custom-source="${t.source||"local"}">
      <a class="lesson-card__link" href="lesson.html?custom=${encodeURIComponent(t.id)}">
        
        <h3 class="lesson-card__title">${q(t.title)}</h3>
        <p class="lesson-card__description">${q(c||"Урок містить кілька тем.")}</p>
        
        <span class="lesson-card__cta">Відкрити комбінований урок</span>
      </a>
    </article>
  `}function j(){return Array.isArray(p)?p.filter(t=>t&&typeof t=="object"&&t.id).map((t,e)=>({...t,topicIds:Array.isArray(t.topicIds)?[...t.topicIds]:[],source:"preset",sortIndex:e})):[]}function R(){return A().filter(t=>t&&typeof t=="object"&&t.id).map((t,e)=>({...t,topicIds:Array.isArray(t.topicIds)?[...t.topicIds]:[],source:"local",sortIndex:1e3+e}))}function M(){const t=new Map;return j().forEach(e=>{t.has(e.id)||t.set(e.id,e)}),R().forEach(e=>{t.set(e.id,e)}),Array.from(t.values())}function C(){if(!g||!y)return;const t=c=>{const a=c?new Date(c).getTime():0;return Number.isFinite(a)?a:0},e=M().sort((c,a)=>{const o=t(a.createdAt)-t(c.createdAt);return o!==0?o:(c.sortIndex||0)-(a.sortIndex||0)});if(!e.length){g.innerHTML="",y.hidden=!1,d&&(d.dataset.hasCustom="false");return}y.hidden=!0,g.innerHTML=e.map(b).join(""),d&&(d.dataset.hasCustom="true")}function U(){const t=S(n.search);return u.filter(c=>{const a=n.category==="all"||c.category===n.category,o=n.level==="all"||c.level===n.level;if(!t)return a&&o;const r=[c.title,c.description,...c.tags??[]].filter(Boolean).map(l=>S(String(l))).some(l=>l.includes(t));return a&&o&&r}).reduce((c,a)=>(c[a.category]||(c[a.category]=[]),c[a.category].push(a),c),{grammar:[],communication:[],lexical:[],quick:[]})}function m(){const t=U();Object.entries(t).forEach(([e,c])=>{const a=$[e],o=I[e],i=k[e];if(!a||!o||!i)return;a.innerHTML=c.map(E).join("");const r=c.length===0;o.hidden=!r,r?a.setAttribute("data-empty","true"):a.removeAttribute("data-empty");const l=n.category!=="all"&&n.category!==e;i.hidden=l})}function w(){s.total&&(s.total.textContent=String(u.length)),s.grammar&&(s.grammar.textContent=String(u.filter(t=>t.category==="grammar").length)),s.communication&&(s.communication.textContent=String(u.filter(t=>t.category==="communication").length)),s.lexical&&(s.lexical.textContent=String(u.filter(t=>t.category==="lexical").length)),s.quick&&(s.quick.textContent=String(u.filter(t=>t.category==="quick").length))}function H(t){n.search=t.target.value,m()}function B(t){n.level=t.target.value,m()}function D(t){const e=t.currentTarget.dataset.category;e&&(n.category=e,x(),m())}function P(){const t=document.querySelector('[data-component="copyright-year"]');t&&(t.textContent=String(new Date().getFullYear()))}function Y(){w(),x(),m(),C(),P(),f&&f.addEventListener("input",H),h&&h.addEventListener("change",B),v.forEach(t=>{t.addEventListener("click",D)}),_(()=>{C()})}Y();
//# sourceMappingURL=index.js.map
