import"./assets/main-Dnzr3yj7.js";import{s as L,l,b as A,a as $}from"./assets/custom-lessons-store-DyP-EnS8.js";import{c as p}from"./assets/custom-lesson-presets-gU5JSAO6.js";const n={search:"",category:"all",level:"all"},f=document.querySelector('[data-filter="search"]'),h=document.querySelector('[data-filter="level"]'),v=Array.from(document.querySelectorAll("[data-category]")),k={grammar:document.querySelector('[data-category-grid="grammar"]'),communication:document.querySelector('[data-category-grid="communication"]'),quick:document.querySelector('[data-category-grid="quick"]')},I={grammar:document.querySelector('[data-category-section="grammar"]'),communication:document.querySelector('[data-category-section="communication"]'),quick:document.querySelector('[data-category-section="quick"]')},E={grammar:document.querySelector('[data-category-empty="grammar"]'),communication:document.querySelector('[data-category-empty="communication"]'),quick:document.querySelector('[data-category-empty="quick"]')},d=document.querySelector("[data-custom-section]"),g=document.querySelector("[data-custom-grid]"),y=document.querySelector("[data-custom-empty]"),s={total:document.querySelector("[data-stat-total]"),grammar:document.querySelector("[data-stat-grammar]"),communication:document.querySelector("[data-stat-communication]"),quick:document.querySelector("[data-stat-quick]")};function S(t){return t.trim().toLowerCase()}function q(t){return String(t??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function _(){v.forEach(t=>{const e=t.dataset.category===n.category,a=t.dataset.category==="all"?n.category==="all":e;t.classList.toggle("chip--filled",a),t.setAttribute("aria-pressed",String(a))})}function T(t){var c;const e=((c=A[t.category])==null?void 0:c.label)??t.category,r=`lesson.html?topic=${encodeURIComponent(t.id)}&category=${encodeURIComponent(t.category)}&level=${encodeURIComponent(t.level)}&title=${encodeURIComponent(t.title)}&file=${encodeURIComponent(t.htmlPath)}`,a=Array.isArray(t.tags)?t.tags:[];return`
    <article class="lesson-card" data-lesson-id="${t.id}" data-category="${t.category}" data-level="${t.level}">
      <a class="lesson-card__link" href="${r}">
        <div class="lesson-card__meta">
          <span class="lesson-card__category">${e}</span>
          <span class="lesson-card__level" aria-label="Рівень">${t.level}</span>
        </div>
        <h3 class="lesson-card__title">${t.title}</h3>
        <p class="lesson-card__description">${t.description}</p>
        ${a.length?`<ul class="lesson-card__tags">${a.map(o=>`<li>${o}</li>`).join("")}</ul>`:""}
        <span class="lesson-card__cta">Перейти до матеріалу</span>
      </a>
    </article>
  `}function b(t){const e=(t.topicIds||[]).map(o=>l.find(i=>i.id===o)).filter(Boolean),r=Array.from(new Set(e.map(o=>o.level))).sort(),a=e.filter(o=>o.category==="grammar").length,c=e.filter(o=>o.category==="communication").length;return{topics:e,levels:r,grammarCount:a,communicationCount:c}}function x(t){const e=b(t),r=t.description||e.topics.map(a=>a.title).slice(0,3).join(", ");return t.level||e.levels.length&&e.levels.join(", "),t.source,`
    <article class="lesson-card lesson-card--custom" data-custom-lesson-id="${t.id}" data-custom-source="${t.source||"local"}">
      <a class="lesson-card__link" href="lesson.html?custom=${encodeURIComponent(t.id)}">
        
        <h3 class="lesson-card__title">${q(t.title)}</h3>
        <p class="lesson-card__description">${q(r||"Урок містить кілька тем.")}</p>
        
        <span class="lesson-card__cta">Відкрити комбінований урок</span>
      </a>
    </article>
  `}function j(){return Array.isArray(p)?p.filter(t=>t&&typeof t=="object"&&t.id).map((t,e)=>({...t,topicIds:Array.isArray(t.topicIds)?[...t.topicIds]:[],source:"preset",sortIndex:e})):[]}function R(){return $().filter(t=>t&&typeof t=="object"&&t.id).map((t,e)=>({...t,topicIds:Array.isArray(t.topicIds)?[...t.topicIds]:[],source:"local",sortIndex:1e3+e}))}function M(){const t=new Map;return j().forEach(e=>{t.has(e.id)||t.set(e.id,e)}),R().forEach(e=>{t.set(e.id,e)}),Array.from(t.values())}function C(){if(!g||!y)return;const t=r=>{const a=r?new Date(r).getTime():0;return Number.isFinite(a)?a:0},e=M().sort((r,a)=>{const c=t(a.createdAt)-t(r.createdAt);return c!==0?c:(r.sortIndex||0)-(a.sortIndex||0)});if(!e.length){g.innerHTML="",y.hidden=!1,d&&(d.dataset.hasCustom="false");return}y.hidden=!0,g.innerHTML=e.map(x).join(""),d&&(d.dataset.hasCustom="true")}function U(){const t=S(n.search);return l.filter(r=>{const a=n.category==="all"||r.category===n.category,c=n.level==="all"||r.level===n.level;if(!t)return a&&c;const i=[r.title,r.description,...r.tags??[]].filter(Boolean).map(u=>S(String(u))).some(u=>u.includes(t));return a&&c&&i}).reduce((r,a)=>(r[a.category]||(r[a.category]=[]),r[a.category].push(a),r),{grammar:[],communication:[],quick:[]})}function m(){const t=U();Object.entries(t).forEach(([e,r])=>{const a=k[e],c=E[e],o=I[e];if(!a||!c||!o)return;a.innerHTML=r.map(T).join("");const i=r.length===0;c.hidden=!i,i?a.setAttribute("data-empty","true"):a.removeAttribute("data-empty");const u=n.category!=="all"&&n.category!==e;o.hidden=u})}function w(){s.total&&(s.total.textContent=String(l.length)),s.grammar&&(s.grammar.textContent=String(l.filter(t=>t.category==="grammar").length)),s.communication&&(s.communication.textContent=String(l.filter(t=>t.category==="communication").length)),s.quick&&(s.quick.textContent=String(l.filter(t=>t.category==="quick").length))}function H(t){n.search=t.target.value,m()}function B(t){n.level=t.target.value,m()}function D(t){const e=t.currentTarget.dataset.category;e&&(n.category=e,_(),m())}function P(){const t=document.querySelector('[data-component="copyright-year"]');t&&(t.textContent=String(new Date().getFullYear()))}function Y(){w(),_(),m(),C(),P(),f&&f.addEventListener("input",H),h&&h.addEventListener("change",B),v.forEach(t=>{t.addEventListener("click",D)}),L(()=>{C()})}Y();
//# sourceMappingURL=index.js.map
